name: DamageIndicator
main: ZenSageX444\DamageIndicator\Damage
version: 1.0
api: 5.0.0
author: ゼンセージ_X, DARUMA/んひた
website: https://github.com/ZenSageX444/DamageIndicator
discord: https://discord.com/invite/NDD6PeJZNC
